/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorEnvelope,
} from '../models/index';
import {
    ErrorEnvelopeFromJSON,
    ErrorEnvelopeToJSON,
} from '../models/index';

export interface DownloadRequest {
    token: string;
}

/**
 * DownloadsApi - interface
 * 
 * @export
 * @interface DownloadsApiInterface
 */
export interface DownloadsApiInterface {
    /**
     * Creates request options for download without sending the request
     * @param {string} token HMAC-signed download token encoding the object key and expiry.
     * @throws {RequiredError}
     * @memberof DownloadsApiInterface
     */
    downloadRequestOpts(requestParameters: DownloadRequest): Promise<runtime.RequestOpts>;

    /**
     * Serves the encoded output file. No Authorization header required -- the HMAC-signed token (generated by GET /v1/jobs/{id}/output) IS the credential. Tokens expire after 24 hours. 
     * @summary Download an output file via signed token
     * @param {string} token HMAC-signed download token encoding the object key and expiry.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DownloadsApiInterface
     */
    downloadRaw(requestParameters: DownloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     * Serves the encoded output file. No Authorization header required -- the HMAC-signed token (generated by GET /v1/jobs/{id}/output) IS the credential. Tokens expire after 24 hours. 
     * Download an output file via signed token
     */
    download(requestParameters: DownloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob>;

}

/**
 * 
 */
export class DownloadsApi extends runtime.BaseAPI implements DownloadsApiInterface {

    /**
     * Creates request options for download without sending the request
     */
    async downloadRequestOpts(requestParameters: DownloadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling download().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/downloads/{token}`;
        urlPath = urlPath.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Serves the encoded output file. No Authorization header required -- the HMAC-signed token (generated by GET /v1/jobs/{id}/output) IS the credential. Tokens expire after 24 hours. 
     * Download an output file via signed token
     */
    async downloadRaw(requestParameters: DownloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const requestOptions = await this.downloadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Serves the encoded output file. No Authorization header required -- the HMAC-signed token (generated by GET /v1/jobs/{id}/output) IS the credential. Tokens expire after 24 hours. 
     * Download an output file via signed token
     */
    async download(requestParameters: DownloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.downloadRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
