/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ReadyResponse,
} from '../models/index';
import {
    ReadyResponseFromJSON,
    ReadyResponseToJSON,
} from '../models/index';

/**
 * HealthApi - interface
 * 
 * @export
 * @interface HealthApiInterface
 */
export interface HealthApiInterface {
    /**
     * Creates request options for healthz without sending the request
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    healthzRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Always returns 200. Used by load balancers and orchestrators.
     * @summary Liveness probe
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    healthzRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Always returns 200. Used by load balancers and orchestrators.
     * Liveness probe
     */
    healthz(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for readyz without sending the request
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    readyzRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Returns 200 when the service is ready to accept traffic. Checks database connectivity, disk headroom (warning and critical thresholds), worker liveness, and drain state. 
     * @summary Readiness probe
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    readyzRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReadyResponse>>;

    /**
     * Returns 200 when the service is ready to accept traffic. Checks database connectivity, disk headroom (warning and critical thresholds), worker liveness, and drain state. 
     * Readiness probe
     */
    readyz(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReadyResponse>;

}

/**
 * 
 */
export class HealthApi extends runtime.BaseAPI implements HealthApiInterface {

    /**
     * Creates request options for healthz without sending the request
     */
    async healthzRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/healthz`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Always returns 200. Used by load balancers and orchestrators.
     * Liveness probe
     */
    async healthzRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.healthzRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Always returns 200. Used by load balancers and orchestrators.
     * Liveness probe
     */
    async healthz(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.healthzRaw(initOverrides);
    }

    /**
     * Creates request options for readyz without sending the request
     */
    async readyzRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/readyz`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns 200 when the service is ready to accept traffic. Checks database connectivity, disk headroom (warning and critical thresholds), worker liveness, and drain state. 
     * Readiness probe
     */
    async readyzRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReadyResponse>> {
        const requestOptions = await this.readyzRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadyResponseFromJSON(jsonValue));
    }

    /**
     * Returns 200 when the service is ready to accept traffic. Checks database connectivity, disk headroom (warning and critical thresholds), worker liveness, and drain state. 
     * Readiness probe
     */
    async readyz(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReadyResponse> {
        const response = await this.readyzRaw(initOverrides);
        return await response.value();
    }

}
