/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateJobRequest,
  ErrorEnvelope,
  JobResponse,
  JobStatus,
  ListJobsResponse,
} from '../models/index';
import {
    CreateJobRequestFromJSON,
    CreateJobRequestToJSON,
    ErrorEnvelopeFromJSON,
    ErrorEnvelopeToJSON,
    JobResponseFromJSON,
    JobResponseToJSON,
    JobStatusFromJSON,
    JobStatusToJSON,
    ListJobsResponseFromJSON,
    ListJobsResponseToJSON,
} from '../models/index';

export interface CancelJobRequest {
    id: string;
}

export interface CreateJobOperationRequest {
    idempotencyKey: string;
    createJobRequest: CreateJobRequest;
}

export interface GetJobRequest {
    id: string;
}

export interface GetJobOutputRequest {
    id: string;
}

export interface ListJobsRequest {
    status?: JobStatus;
    limit?: number;
    cursor?: string;
}

/**
 * JobsApi - interface
 * 
 * @export
 * @interface JobsApiInterface
 */
export interface JobsApiInterface {
    /**
     * Creates request options for cancelJob without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    cancelJobRequestOpts(requestParameters: CancelJobRequest): Promise<runtime.RequestOpts>;

    /**
     * Cancels a job in a non-terminal state (queued, probing, encoding, muxing, uploading_output). Returns 409 if the job is already completed, failed, or canceled. 
     * @summary Cancel a job
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    cancelJobRaw(requestParameters: CancelJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobResponse>>;

    /**
     * Cancels a job in a non-terminal state (queued, probing, encoding, muxing, uploading_output). Returns 409 if the job is already completed, failed, or canceled. 
     * Cancel a job
     */
    cancelJob(requestParameters: CancelJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobResponse>;

    /**
     * Creates request options for createJob without sending the request
     * @param {string} idempotencyKey Client-generated UUID or string for exactly-once semantics. Required on all POST endpoints. Replaying the same key with the same request body returns the original response without side effects. 
     * @param {CreateJobRequest} createJobRequest 
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    createJobRequestOpts(requestParameters: CreateJobOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a queued encoding job from a completed upload source. The `profile` field accepts explicit coffee profiles or `sophon-auto`, and `output.target_height` can request aspect-preserving downscale. 
     * @summary Submit an encoding job
     * @param {string} idempotencyKey Client-generated UUID or string for exactly-once semantics. Required on all POST endpoints. Replaying the same key with the same request body returns the original response without side effects. 
     * @param {CreateJobRequest} createJobRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    createJobRaw(requestParameters: CreateJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobResponse>>;

    /**
     * Creates a queued encoding job from a completed upload source. The `profile` field accepts explicit coffee profiles or `sophon-auto`, and `output.target_height` can request aspect-preserving downscale. 
     * Submit an encoding job
     */
    createJob(requestParameters: CreateJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobResponse>;

    /**
     * Creates request options for getJob without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    getJobRequestOpts(requestParameters: GetJobRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns current job state, progress, source metadata, resolved adaptive profile information, and output availability for one job. 
     * @summary Get a single job by ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    getJobRaw(requestParameters: GetJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobResponse>>;

    /**
     * Returns current job state, progress, source metadata, resolved adaptive profile information, and output availability for one job. 
     * Get a single job by ID
     */
    getJob(requestParameters: GetJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobResponse>;

    /**
     * Creates request options for getJobOutput without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    getJobOutputRequestOpts(requestParameters: GetJobOutputRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns a 302 redirect to a signed download URL for the job\'s output file. The signed URL is valid for 24 hours. 
     * @summary Get the encoded output file
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    getJobOutputRaw(requestParameters: GetJobOutputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Returns a 302 redirect to a signed download URL for the job\'s output file. The signed URL is valid for 24 hours. 
     * Get the encoded output file
     */
    getJobOutput(requestParameters: GetJobOutputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for listJobs without sending the request
     * @param {JobStatus} [status] Filter by job status.
     * @param {number} [limit] Maximum number of items to return per page.
     * @param {string} [cursor] Opaque pagination cursor returned in a previous response\&#39;s &#x60;next_cursor&#x60; field.
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    listJobsRequestOpts(requestParameters: ListJobsRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns jobs for the authenticated organization ordered by creation time, with optional status filtering and opaque cursor pagination. 
     * @summary List jobs with cursor pagination
     * @param {JobStatus} [status] Filter by job status.
     * @param {number} [limit] Maximum number of items to return per page.
     * @param {string} [cursor] Opaque pagination cursor returned in a previous response\&#39;s &#x60;next_cursor&#x60; field.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobsApiInterface
     */
    listJobsRaw(requestParameters: ListJobsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListJobsResponse>>;

    /**
     * Returns jobs for the authenticated organization ordered by creation time, with optional status filtering and opaque cursor pagination. 
     * List jobs with cursor pagination
     */
    listJobs(requestParameters: ListJobsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListJobsResponse>;

}

/**
 * 
 */
export class JobsApi extends runtime.BaseAPI implements JobsApiInterface {

    /**
     * Creates request options for cancelJob without sending the request
     */
    async cancelJobRequestOpts(requestParameters: CancelJobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cancelJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerApiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/jobs/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancels a job in a non-terminal state (queued, probing, encoding, muxing, uploading_output). Returns 409 if the job is already completed, failed, or canceled. 
     * Cancel a job
     */
    async cancelJobRaw(requestParameters: CancelJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobResponse>> {
        const requestOptions = await this.cancelJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobResponseFromJSON(jsonValue));
    }

    /**
     * Cancels a job in a non-terminal state (queued, probing, encoding, muxing, uploading_output). Returns 409 if the job is already completed, failed, or canceled. 
     * Cancel a job
     */
    async cancelJob(requestParameters: CancelJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobResponse> {
        const response = await this.cancelJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createJob without sending the request
     */
    async createJobRequestOpts(requestParameters: CreateJobOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createJob().'
            );
        }

        if (requestParameters['createJobRequest'] == null) {
            throw new runtime.RequiredError(
                'createJobRequest',
                'Required parameter "createJobRequest" was null or undefined when calling createJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerApiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/jobs`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateJobRequestToJSON(requestParameters['createJobRequest']),
        };
    }

    /**
     * Creates a queued encoding job from a completed upload source. The `profile` field accepts explicit coffee profiles or `sophon-auto`, and `output.target_height` can request aspect-preserving downscale. 
     * Submit an encoding job
     */
    async createJobRaw(requestParameters: CreateJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobResponse>> {
        const requestOptions = await this.createJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobResponseFromJSON(jsonValue));
    }

    /**
     * Creates a queued encoding job from a completed upload source. The `profile` field accepts explicit coffee profiles or `sophon-auto`, and `output.target_height` can request aspect-preserving downscale. 
     * Submit an encoding job
     */
    async createJob(requestParameters: CreateJobOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobResponse> {
        const response = await this.createJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getJob without sending the request
     */
    async getJobRequestOpts(requestParameters: GetJobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerApiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/jobs/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns current job state, progress, source metadata, resolved adaptive profile information, and output availability for one job. 
     * Get a single job by ID
     */
    async getJobRaw(requestParameters: GetJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JobResponse>> {
        const requestOptions = await this.getJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JobResponseFromJSON(jsonValue));
    }

    /**
     * Returns current job state, progress, source metadata, resolved adaptive profile information, and output availability for one job. 
     * Get a single job by ID
     */
    async getJob(requestParameters: GetJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JobResponse> {
        const response = await this.getJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getJobOutput without sending the request
     */
    async getJobOutputRequestOpts(requestParameters: GetJobOutputRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getJobOutput().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerApiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/jobs/{id}/output`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns a 302 redirect to a signed download URL for the job\'s output file. The signed URL is valid for 24 hours. 
     * Get the encoded output file
     */
    async getJobOutputRaw(requestParameters: GetJobOutputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.getJobOutputRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Returns a 302 redirect to a signed download URL for the job\'s output file. The signed URL is valid for 24 hours. 
     * Get the encoded output file
     */
    async getJobOutput(requestParameters: GetJobOutputRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getJobOutputRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for listJobs without sending the request
     */
    async listJobsRequestOpts(requestParameters: ListJobsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerApiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/jobs`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns jobs for the authenticated organization ordered by creation time, with optional status filtering and opaque cursor pagination. 
     * List jobs with cursor pagination
     */
    async listJobsRaw(requestParameters: ListJobsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListJobsResponse>> {
        const requestOptions = await this.listJobsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListJobsResponseFromJSON(jsonValue));
    }

    /**
     * Returns jobs for the authenticated organization ordered by creation time, with optional status filtering and opaque cursor pagination. 
     * List jobs with cursor pagination
     */
    async listJobs(requestParameters: ListJobsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListJobsResponse> {
        const response = await this.listJobsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
