/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CompleteUploadResponse,
  CreateUploadRequest,
  CreateUploadResponse,
  ErrorEnvelope,
  UploadPartResponse,
  UploadStatusResponse,
} from '../models/index';
import {
    CompleteUploadResponseFromJSON,
    CompleteUploadResponseToJSON,
    CreateUploadRequestFromJSON,
    CreateUploadRequestToJSON,
    CreateUploadResponseFromJSON,
    CreateUploadResponseToJSON,
    ErrorEnvelopeFromJSON,
    ErrorEnvelopeToJSON,
    UploadPartResponseFromJSON,
    UploadPartResponseToJSON,
    UploadStatusResponseFromJSON,
    UploadStatusResponseToJSON,
} from '../models/index';

export interface CancelUploadRequest {
    id: string;
}

export interface CompleteUploadRequest {
    id: string;
    idempotencyKey: string;
}

export interface CreateUploadOperationRequest {
    idempotencyKey: string;
    createUploadRequest: CreateUploadRequest;
}

export interface GetUploadRequest {
    id: string;
}

export interface UploadPartRequest {
    id: string;
    partNumber: number;
    body: Blob;
}

/**
 * UploadsApi - interface
 * 
 * @export
 * @interface UploadsApiInterface
 */
export interface UploadsApiInterface {
    /**
     * Creates request options for cancelUpload without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    cancelUploadRequestOpts(requestParameters: CancelUploadRequest): Promise<runtime.RequestOpts>;

    /**
     * Sets the upload session to canceled and deletes staged chunks from disk. 
     * @summary Cancel an upload session
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    cancelUploadRaw(requestParameters: CancelUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Sets the upload session to canceled and deletes staged chunks from disk. 
     * Cancel an upload session
     */
    cancelUpload(requestParameters: CancelUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for completeUpload without sending the request
     * @param {string} id 
     * @param {string} idempotencyKey Client-generated UUID or string for exactly-once semantics. Required on all POST endpoints. Replaying the same key with the same request body returns the original response without side effects. 
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    completeUploadRequestOpts(requestParameters: CompleteUploadRequest): Promise<runtime.RequestOpts>;

    /**
     * Assembles all received chunks into a single file, validates size matches the declared file_size, probes with ffprobe, and transitions the session to completed. 
     * @summary Finalize a chunked upload
     * @param {string} id 
     * @param {string} idempotencyKey Client-generated UUID or string for exactly-once semantics. Required on all POST endpoints. Replaying the same key with the same request body returns the original response without side effects. 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    completeUploadRaw(requestParameters: CompleteUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompleteUploadResponse>>;

    /**
     * Assembles all received chunks into a single file, validates size matches the declared file_size, probes with ffprobe, and transitions the session to completed. 
     * Finalize a chunked upload
     */
    completeUpload(requestParameters: CompleteUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompleteUploadResponse>;

    /**
     * Creates request options for createUpload without sending the request
     * @param {string} idempotencyKey Client-generated UUID or string for exactly-once semantics. Required on all POST endpoints. Replaying the same key with the same request body returns the original response without side effects. 
     * @param {CreateUploadRequest} createUploadRequest 
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    createUploadRequestOpts(requestParameters: CreateUploadOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Starts a resumable source upload and returns the chunk size, chunk count, session ID, and expiration timestamp. 
     * @summary Initialize a chunked upload session
     * @param {string} idempotencyKey Client-generated UUID or string for exactly-once semantics. Required on all POST endpoints. Replaying the same key with the same request body returns the original response without side effects. 
     * @param {CreateUploadRequest} createUploadRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    createUploadRaw(requestParameters: CreateUploadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateUploadResponse>>;

    /**
     * Starts a resumable source upload and returns the chunk size, chunk count, session ID, and expiration timestamp. 
     * Initialize a chunked upload session
     */
    createUpload(requestParameters: CreateUploadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateUploadResponse>;

    /**
     * Creates request options for getUpload without sending the request
     * @param {string} id 
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    getUploadRequestOpts(requestParameters: GetUploadRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns received chunks and, after assembly/probe, source dimensions and duration used by downstream budget and encoding decisions. 
     * @summary Get upload session status
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    getUploadRaw(requestParameters: GetUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadStatusResponse>>;

    /**
     * Returns received chunks and, after assembly/probe, source dimensions and duration used by downstream budget and encoding decisions. 
     * Get upload session status
     */
    getUpload(requestParameters: GetUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadStatusResponse>;

    /**
     * Creates request options for uploadPart without sending the request
     * @param {string} id 
     * @param {number} partNumber 
     * @param {Blob} body 
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    uploadPartRequestOpts(requestParameters: UploadPartRequest): Promise<runtime.RequestOpts>;

    /**
     * Streams the chunk body to disk. Part numbers are 0-indexed. Uploading the same part number again is idempotent (returns success without re-writing). 
     * @summary Upload a single chunk
     * @param {string} id 
     * @param {number} partNumber 
     * @param {Blob} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadsApiInterface
     */
    uploadPartRaw(requestParameters: UploadPartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadPartResponse>>;

    /**
     * Streams the chunk body to disk. Part numbers are 0-indexed. Uploading the same part number again is idempotent (returns success without re-writing). 
     * Upload a single chunk
     */
    uploadPart(requestParameters: UploadPartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadPartResponse>;

}

/**
 * 
 */
export class UploadsApi extends runtime.BaseAPI implements UploadsApiInterface {

    /**
     * Creates request options for cancelUpload without sending the request
     */
    async cancelUploadRequestOpts(requestParameters: CancelUploadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cancelUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerApiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/uploads/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Sets the upload session to canceled and deletes staged chunks from disk. 
     * Cancel an upload session
     */
    async cancelUploadRaw(requestParameters: CancelUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.cancelUploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Sets the upload session to canceled and deletes staged chunks from disk. 
     * Cancel an upload session
     */
    async cancelUpload(requestParameters: CancelUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.cancelUploadRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for completeUpload without sending the request
     */
    async completeUploadRequestOpts(requestParameters: CompleteUploadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling completeUpload().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling completeUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerApiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/uploads/{id}/complete`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Assembles all received chunks into a single file, validates size matches the declared file_size, probes with ffprobe, and transitions the session to completed. 
     * Finalize a chunked upload
     */
    async completeUploadRaw(requestParameters: CompleteUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompleteUploadResponse>> {
        const requestOptions = await this.completeUploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompleteUploadResponseFromJSON(jsonValue));
    }

    /**
     * Assembles all received chunks into a single file, validates size matches the declared file_size, probes with ffprobe, and transitions the session to completed. 
     * Finalize a chunked upload
     */
    async completeUpload(requestParameters: CompleteUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompleteUploadResponse> {
        const response = await this.completeUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createUpload without sending the request
     */
    async createUploadRequestOpts(requestParameters: CreateUploadOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createUpload().'
            );
        }

        if (requestParameters['createUploadRequest'] == null) {
            throw new runtime.RequiredError(
                'createUploadRequest',
                'Required parameter "createUploadRequest" was null or undefined when calling createUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerApiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/uploads`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateUploadRequestToJSON(requestParameters['createUploadRequest']),
        };
    }

    /**
     * Starts a resumable source upload and returns the chunk size, chunk count, session ID, and expiration timestamp. 
     * Initialize a chunked upload session
     */
    async createUploadRaw(requestParameters: CreateUploadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateUploadResponse>> {
        const requestOptions = await this.createUploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateUploadResponseFromJSON(jsonValue));
    }

    /**
     * Starts a resumable source upload and returns the chunk size, chunk count, session ID, and expiration timestamp. 
     * Initialize a chunked upload session
     */
    async createUpload(requestParameters: CreateUploadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateUploadResponse> {
        const response = await this.createUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getUpload without sending the request
     */
    async getUploadRequestOpts(requestParameters: GetUploadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerApiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/uploads/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns received chunks and, after assembly/probe, source dimensions and duration used by downstream budget and encoding decisions. 
     * Get upload session status
     */
    async getUploadRaw(requestParameters: GetUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadStatusResponse>> {
        const requestOptions = await this.getUploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadStatusResponseFromJSON(jsonValue));
    }

    /**
     * Returns received chunks and, after assembly/probe, source dimensions and duration used by downstream budget and encoding decisions. 
     * Get upload session status
     */
    async getUpload(requestParameters: GetUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadStatusResponse> {
        const response = await this.getUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for uploadPart without sending the request
     */
    async uploadPartRequestOpts(requestParameters: UploadPartRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling uploadPart().'
            );
        }

        if (requestParameters['partNumber'] == null) {
            throw new runtime.RequiredError(
                'partNumber',
                'Required parameter "partNumber" was null or undefined when calling uploadPart().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling uploadPart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/octet-stream';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerApiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/uploads/{id}/parts/{part_number}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"part_number"}}`, encodeURIComponent(String(requestParameters['partNumber'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Streams the chunk body to disk. Part numbers are 0-indexed. Uploading the same part number again is idempotent (returns success without re-writing). 
     * Upload a single chunk
     */
    async uploadPartRaw(requestParameters: UploadPartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadPartResponse>> {
        const requestOptions = await this.uploadPartRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadPartResponseFromJSON(jsonValue));
    }

    /**
     * Streams the chunk body to disk. Part numbers are 0-indexed. Uploading the same part number again is idempotent (returns success without re-writing). 
     * Upload a single chunk
     */
    async uploadPart(requestParameters: UploadPartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadPartResponse> {
        const response = await this.uploadPartRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
