/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompleteUploadResponse
 */
export interface CompleteUploadResponse {
    /**
     * 
     * @type {string}
     * @memberof CompleteUploadResponse
     */
    id: string;
    /**
     * 
     * @type {CompleteUploadResponseStatusEnum}
     * @memberof CompleteUploadResponse
     */
    status: CompleteUploadResponseStatusEnum;
    /**
     * SHA-256 hex digest of the assembled file.
     * @type {string}
     * @memberof CompleteUploadResponse
     */
    sha256: string;
    /**
     * 
     * @type {number}
     * @memberof CompleteUploadResponse
     */
    bytes: number;
}

/**
* @export
* @enum {string}
*/
export enum CompleteUploadResponseStatusEnum {
    COMPLETED = 'completed'
}


/**
 * Check if a given object implements the CompleteUploadResponse interface.
 */
export function instanceOfCompleteUploadResponse(value: object): value is CompleteUploadResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('sha256' in value) || value['sha256'] === undefined) return false;
    if (!('bytes' in value) || value['bytes'] === undefined) return false;
    return true;
}

export function CompleteUploadResponseFromJSON(json: any): CompleteUploadResponse {
    return CompleteUploadResponseFromJSONTyped(json, false);
}

export function CompleteUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteUploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'sha256': json['sha256'],
        'bytes': json['bytes'],
    };
}

export function CompleteUploadResponseToJSON(json: any): CompleteUploadResponse {
    return CompleteUploadResponseToJSONTyped(json, false);
}

export function CompleteUploadResponseToJSONTyped(value?: CompleteUploadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'sha256': value['sha256'],
        'bytes': value['bytes'],
    };
}

