/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateJobOutputOptions } from './CreateJobOutputOptions';
import {
    CreateJobOutputOptionsFromJSON,
    CreateJobOutputOptionsFromJSONTyped,
    CreateJobOutputOptionsToJSON,
    CreateJobOutputOptionsToJSONTyped,
} from './CreateJobOutputOptions';
import type { JobProfile } from './JobProfile';
import {
    JobProfileFromJSON,
    JobProfileFromJSONTyped,
    JobProfileToJSON,
    JobProfileToJSONTyped,
} from './JobProfile';
import type { UploadJobSource } from './UploadJobSource';
import {
    UploadJobSourceFromJSON,
    UploadJobSourceFromJSONTyped,
    UploadJobSourceToJSON,
    UploadJobSourceToJSONTyped,
} from './UploadJobSource';

/**
 * 
 * @export
 * @interface CreateJobRequest
 */
export interface CreateJobRequest {
    /**
     * 
     * @type {UploadJobSource}
     * @memberof CreateJobRequest
     */
    source: UploadJobSource;
    /**
     * 
     * @type {JobProfile}
     * @memberof CreateJobRequest
     */
    profile: JobProfile;
    /**
     * 
     * @type {CreateJobOutputOptions}
     * @memberof CreateJobRequest
     */
    output?: CreateJobOutputOptions;
    /**
     * IDs of registered webhook endpoints to notify on job state changes.
     * @type {Array<string>}
     * @memberof CreateJobRequest
     */
    webhook_ids?: Array<string>;
    /**
     * Arbitrary key-value metadata attached to the job. Max 16 KiB serialized.
     * @type {{ [key: string]: any; }}
     * @memberof CreateJobRequest
     */
    metadata?: { [key: string]: any; };
}



/**
 * Check if a given object implements the CreateJobRequest interface.
 */
export function instanceOfCreateJobRequest(value: object): value is CreateJobRequest {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('profile' in value) || value['profile'] === undefined) return false;
    return true;
}

export function CreateJobRequestFromJSON(json: any): CreateJobRequest {
    return CreateJobRequestFromJSONTyped(json, false);
}

export function CreateJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'source': UploadJobSourceFromJSON(json['source']),
        'profile': JobProfileFromJSON(json['profile']),
        'output': json['output'] == null ? undefined : CreateJobOutputOptionsFromJSON(json['output']),
        'webhook_ids': json['webhook_ids'] == null ? undefined : json['webhook_ids'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateJobRequestToJSON(json: any): CreateJobRequest {
    return CreateJobRequestToJSONTyped(json, false);
}

export function CreateJobRequestToJSONTyped(value?: CreateJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': UploadJobSourceToJSON(value['source']),
        'profile': JobProfileToJSON(value['profile']),
        'output': CreateJobOutputOptionsToJSON(value['output']),
        'webhook_ids': value['webhook_ids'],
        'metadata': value['metadata'],
    };
}

