/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  ## Client Libraries  For server-side application integrations, start with one of the official SOPHON client libraries. Current published version: `0.1.5`.  | Language | Package | Install | |---|---|---| | TypeScript / JavaScript | [`@liqhtworks/sophon-sdk`](https://www.npmjs.com/package/@liqhtworks/sophon-sdk) | `npm install @liqhtworks/sophon-sdk` | | Python | [`sophon-sdk`](https://pypi.org/project/sophon-sdk/) | `pip install sophon-sdk` | | Go | [`github.com/Liqhtworks/sophon-sdk-go`](https://github.com/Liqhtworks/sophon-sdk-go) | `go get github.com/Liqhtworks/sophon-sdk-go@latest` |  These libraries are generated from this OpenAPI document and include the generated endpoint clients plus helpers for chunked uploads, terminal job polling, upload-backed job source construction, and webhook signature verification.  We do not currently publish official SDKs for Ruby, Java, Kotlin, Swift, PHP, .NET, or Rust. Use the REST API directly from those languages.  Authentication is via Bearer API key or session cookie. Create API keys in the SOPHON dashboard at https://sophon.rs/account/general and pass them as `Authorization: Bearer xt_live_...`. All POST endpoints require an `Idempotency-Key` header. List endpoints use opaque cursor-based pagination.  See **SDKs** for install commands and quickstarts. See **Integration example** for a production state-machine pattern and raw HTTP adapter guidance. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUploadRequest
 */
export interface CreateUploadRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateUploadRequest
     */
    file_name: string;
    /**
     * Total file size in bytes.
     * @type {number}
     * @memberof CreateUploadRequest
     */
    file_size: number;
    /**
     * 
     * @type {string}
     * @memberof CreateUploadRequest
     */
    mime_type: string;
}

/**
 * Check if a given object implements the CreateUploadRequest interface.
 */
export function instanceOfCreateUploadRequest(value: object): value is CreateUploadRequest {
    if (!('file_name' in value) || value['file_name'] === undefined) return false;
    if (!('file_size' in value) || value['file_size'] === undefined) return false;
    if (!('mime_type' in value) || value['mime_type'] === undefined) return false;
    return true;
}

export function CreateUploadRequestFromJSON(json: any): CreateUploadRequest {
    return CreateUploadRequestFromJSONTyped(json, false);
}

export function CreateUploadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUploadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'file_name': json['file_name'],
        'file_size': json['file_size'],
        'mime_type': json['mime_type'],
    };
}

export function CreateUploadRequestToJSON(json: any): CreateUploadRequest {
    return CreateUploadRequestToJSONTyped(json, false);
}

export function CreateUploadRequestToJSONTyped(value?: CreateUploadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_name': value['file_name'],
        'file_size': value['file_size'],
        'mime_type': value['mime_type'],
    };
}

