/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUploadRequest
 */
export interface CreateUploadRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateUploadRequest
     */
    file_name: string;
    /**
     * Total file size in bytes.
     * @type {number}
     * @memberof CreateUploadRequest
     */
    file_size: number;
    /**
     * 
     * @type {string}
     * @memberof CreateUploadRequest
     */
    mime_type: string;
}

/**
 * Check if a given object implements the CreateUploadRequest interface.
 */
export function instanceOfCreateUploadRequest(value: object): value is CreateUploadRequest {
    if (!('file_name' in value) || value['file_name'] === undefined) return false;
    if (!('file_size' in value) || value['file_size'] === undefined) return false;
    if (!('mime_type' in value) || value['mime_type'] === undefined) return false;
    return true;
}

export function CreateUploadRequestFromJSON(json: any): CreateUploadRequest {
    return CreateUploadRequestFromJSONTyped(json, false);
}

export function CreateUploadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUploadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'file_name': json['file_name'],
        'file_size': json['file_size'],
        'mime_type': json['mime_type'],
    };
}

export function CreateUploadRequestToJSON(json: any): CreateUploadRequest {
    return CreateUploadRequestToJSONTyped(json, false);
}

export function CreateUploadRequestToJSONTyped(value?: CreateUploadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_name': value['file_name'],
        'file_size': value['file_size'],
        'mime_type': value['mime_type'],
    };
}

