/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  ## Client Libraries  For server-side application integrations, start with one of the official SOPHON client libraries. Current published version: `0.1.5`.  | Language | Package | Install | |---|---|---| | TypeScript / JavaScript | [`@liqhtworks/sophon-sdk`](https://www.npmjs.com/package/@liqhtworks/sophon-sdk) | `npm install @liqhtworks/sophon-sdk` | | Python | [`sophon-sdk`](https://pypi.org/project/sophon-sdk/) | `pip install sophon-sdk` | | Go | [`github.com/Liqhtworks/sophon-sdk-go`](https://github.com/Liqhtworks/sophon-sdk-go) | `go get github.com/Liqhtworks/sophon-sdk-go@latest` |  These libraries are generated from this OpenAPI document and include the generated endpoint clients plus helpers for chunked uploads, terminal job polling, upload-backed job source construction, and webhook signature verification.  We do not currently publish official SDKs for Ruby, Java, Kotlin, Swift, PHP, .NET, or Rust. Use the REST API directly from those languages.  Authentication is via Bearer API key or session cookie. Create API keys in the SOPHON dashboard at https://sophon.rs/account/general and pass them as `Authorization: Bearer xt_live_...`. All POST endpoints require an `Idempotency-Key` header. List endpoints use opaque cursor-based pagination.  See **SDKs** for install commands and quickstarts. See **Integration example** for a production state-machine pattern and raw HTTP adapter guidance. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateJobOutputOptions } from './CreateJobOutputOptions';
import {
    CreateJobOutputOptionsFromJSON,
    CreateJobOutputOptionsFromJSONTyped,
    CreateJobOutputOptionsToJSON,
    CreateJobOutputOptionsToJSONTyped,
} from './CreateJobOutputOptions';
import type { JobProfile } from './JobProfile';
import {
    JobProfileFromJSON,
    JobProfileFromJSONTyped,
    JobProfileToJSON,
    JobProfileToJSONTyped,
} from './JobProfile';
import type { UploadJobSource } from './UploadJobSource';
import {
    UploadJobSourceFromJSON,
    UploadJobSourceFromJSONTyped,
    UploadJobSourceToJSON,
    UploadJobSourceToJSONTyped,
} from './UploadJobSource';

/**
 * 
 * @export
 * @interface CreateJobRequest
 */
export interface CreateJobRequest {
    /**
     * 
     * @type {UploadJobSource}
     * @memberof CreateJobRequest
     */
    source: UploadJobSource;
    /**
     * 
     * @type {JobProfile}
     * @memberof CreateJobRequest
     */
    profile: JobProfile;
    /**
     * 
     * @type {CreateJobOutputOptions}
     * @memberof CreateJobRequest
     */
    output?: CreateJobOutputOptions;
    /**
     * IDs of registered webhook endpoints to notify on job state changes.
     * @type {Array<string>}
     * @memberof CreateJobRequest
     */
    webhook_ids?: Array<string>;
    /**
     * Arbitrary key-value metadata attached to the job. Max 16 KiB serialized.
     * @type {{ [key: string]: any; }}
     * @memberof CreateJobRequest
     */
    metadata?: { [key: string]: any; };
}



/**
 * Check if a given object implements the CreateJobRequest interface.
 */
export function instanceOfCreateJobRequest(value: object): value is CreateJobRequest {
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('profile' in value) || value['profile'] === undefined) return false;
    return true;
}

export function CreateJobRequestFromJSON(json: any): CreateJobRequest {
    return CreateJobRequestFromJSONTyped(json, false);
}

export function CreateJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'source': UploadJobSourceFromJSON(json['source']),
        'profile': JobProfileFromJSON(json['profile']),
        'output': json['output'] == null ? undefined : CreateJobOutputOptionsFromJSON(json['output']),
        'webhook_ids': json['webhook_ids'] == null ? undefined : json['webhook_ids'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateJobRequestToJSON(json: any): CreateJobRequest {
    return CreateJobRequestToJSONTyped(json, false);
}

export function CreateJobRequestToJSONTyped(value?: CreateJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': UploadJobSourceToJSON(value['source']),
        'profile': JobProfileToJSON(value['profile']),
        'output': CreateJobOutputOptionsToJSON(value['output']),
        'webhook_ids': value['webhook_ids'],
        'metadata': value['metadata'],
    };
}

