/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUploadResponse
 */
export interface CreateUploadResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateUploadResponse
     */
    id: string;
    /**
     * Size of each chunk in bytes. Tiered by file size:
     * <64 MB = whole file, <=1 GB = 8 MB, <=10 GB = 16 MB, >10 GB = 32 MB.
     * 
     * @type {number}
     * @memberof CreateUploadResponse
     */
    chunk_size: number;
    /**
     * 
     * @type {number}
     * @memberof CreateUploadResponse
     */
    total_chunks: number;
    /**
     * Upload session expiry (24 hours from creation).
     * @type {Date}
     * @memberof CreateUploadResponse
     */
    expires_at: Date;
}

/**
 * Check if a given object implements the CreateUploadResponse interface.
 */
export function instanceOfCreateUploadResponse(value: object): value is CreateUploadResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('chunk_size' in value) || value['chunk_size'] === undefined) return false;
    if (!('total_chunks' in value) || value['total_chunks'] === undefined) return false;
    if (!('expires_at' in value) || value['expires_at'] === undefined) return false;
    return true;
}

export function CreateUploadResponseFromJSON(json: any): CreateUploadResponse {
    return CreateUploadResponseFromJSONTyped(json, false);
}

export function CreateUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'chunk_size': json['chunk_size'],
        'total_chunks': json['total_chunks'],
        'expires_at': (new Date(json['expires_at'])),
    };
}

export function CreateUploadResponseToJSON(json: any): CreateUploadResponse {
    return CreateUploadResponseToJSONTyped(json, false);
}

export function CreateUploadResponseToJSONTyped(value?: CreateUploadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'chunk_size': value['chunk_size'],
        'total_chunks': value['total_chunks'],
        'expires_at': value['expires_at'].toISOString(),
    };
}

