/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OutputContainer } from './OutputContainer';
import {
    OutputContainerFromJSON,
    OutputContainerFromJSONTyped,
    OutputContainerToJSON,
    OutputContainerToJSONTyped,
} from './OutputContainer';

/**
 * Optional output shaping knobs for a new job.
 * @export
 * @interface CreateJobOutputOptions
 */
export interface CreateJobOutputOptions {
    /**
     * 
     * @type {OutputContainer}
     * @memberof CreateJobOutputOptions
     */
    container?: OutputContainer;
    /**
     * When true, audio is included in the output. MKV preserves
     * source audio streams unchanged. MP4 preserves broadly compatible
     * source audio codecs when possible, and may normalize
     * incompatible codecs to AAC for playback compatibility.
     * When false, the output is video only.
     * 
     * @type {boolean}
     * @memberof CreateJobOutputOptions
     */
    audio?: boolean;
    /**
     * Target output height in pixels. When set, output is scaled down
     * (aspect ratio preserved, width derived from source, both dims
     * rounded to even). If absent or larger than source height, output
     * uses source dimensions. Billing tier is determined by the actual
     * encoded output, not by this requested value.
     * 
     * @type {number}
     * @memberof CreateJobOutputOptions
     */
    target_height?: number;
}



/**
 * Check if a given object implements the CreateJobOutputOptions interface.
 */
export function instanceOfCreateJobOutputOptions(value: object): value is CreateJobOutputOptions {
    return true;
}

export function CreateJobOutputOptionsFromJSON(json: any): CreateJobOutputOptions {
    return CreateJobOutputOptionsFromJSONTyped(json, false);
}

export function CreateJobOutputOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateJobOutputOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'container': json['container'] == null ? undefined : OutputContainerFromJSON(json['container']),
        'audio': json['audio'] == null ? undefined : json['audio'],
        'target_height': json['target_height'] == null ? undefined : json['target_height'],
    };
}

export function CreateJobOutputOptionsToJSON(json: any): CreateJobOutputOptions {
    return CreateJobOutputOptionsToJSONTyped(json, false);
}

export function CreateJobOutputOptionsToJSONTyped(value?: CreateJobOutputOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'container': OutputContainerToJSON(value['container']),
        'audio': value['audio'],
        'target_height': value['target_height'],
    };
}

