/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWebhookRequest
 */
export interface CreateWebhookRequest {
    /**
     * HTTPS URL to receive webhook deliveries. Must not point to
     * private, loopback, link-local, or multicast addresses (SSRF prevention).
     * 
     * @type {string}
     * @memberof CreateWebhookRequest
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWebhookRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the CreateWebhookRequest interface.
 */
export function instanceOfCreateWebhookRequest(value: object): value is CreateWebhookRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function CreateWebhookRequestFromJSON(json: any): CreateWebhookRequest {
    return CreateWebhookRequestFromJSONTyped(json, false);
}

export function CreateWebhookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CreateWebhookRequestToJSON(json: any): CreateWebhookRequest {
    return CreateWebhookRequestToJSONTyped(json, false);
}

export function CreateWebhookRequestToJSONTyped(value?: CreateWebhookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'name': value['name'],
    };
}

