/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorBody
 */
export interface ErrorBody {
    /**
     * 
     * @type {ErrorBodyCodeEnum}
     * @memberof ErrorBody
     */
    code: ErrorBodyCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof ErrorBody
     */
    message: string;
    /**
     * True for rate_limited, capacity_exceeded, and internal_error.
     * Clients should retry with exponential backoff when true.
     * 
     * @type {boolean}
     * @memberof ErrorBody
     */
    retryable: boolean;
    /**
     * Server-assigned request ID for correlation with logs.
     * @type {string}
     * @memberof ErrorBody
     */
    request_id?: string;
}

/**
* @export
* @enum {string}
*/
export enum ErrorBodyCodeEnum {
    VALIDATION_ERROR = 'validation_error',
    UNAUTHORIZED = 'unauthorized',
    FORBIDDEN = 'forbidden',
    NOT_FOUND = 'not_found',
    CONFLICT = 'conflict',
    RATE_LIMITED = 'rate_limited',
    QUOTA_EXCEEDED = 'quota_exceeded',
    CAPACITY_EXCEEDED = 'capacity_exceeded',
    SOURCE_INVALID = 'source_invalid',
    SOURCE_UNSUPPORTED = 'source_unsupported',
    JOB_NOT_CANCELABLE = 'job_not_cancelable',
    OUTPUT_NOT_READY = 'output_not_ready',
    OUTPUT_PERSISTENCE_FAILED = 'output_persistence_failed',
    INTERNAL_ERROR = 'internal_error'
}


/**
 * Check if a given object implements the ErrorBody interface.
 */
export function instanceOfErrorBody(value: object): value is ErrorBody {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('retryable' in value) || value['retryable'] === undefined) return false;
    return true;
}

export function ErrorBodyFromJSON(json: any): ErrorBody {
    return ErrorBodyFromJSONTyped(json, false);
}

export function ErrorBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorBody {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'retryable': json['retryable'],
        'request_id': json['request_id'] == null ? undefined : json['request_id'],
    };
}

export function ErrorBodyToJSON(json: any): ErrorBody {
    return ErrorBodyToJSONTyped(json, false);
}

export function ErrorBodyToJSONTyped(value?: ErrorBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'retryable': value['retryable'],
        'request_id': value['request_id'],
    };
}

