/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorBody } from './ErrorBody';
import {
    ErrorBodyFromJSON,
    ErrorBodyFromJSONTyped,
    ErrorBodyToJSON,
    ErrorBodyToJSONTyped,
} from './ErrorBody';

/**
 * 
 * @export
 * @interface ErrorEnvelope
 */
export interface ErrorEnvelope {
    /**
     * 
     * @type {ErrorBody}
     * @memberof ErrorEnvelope
     */
    error: ErrorBody;
}

/**
 * Check if a given object implements the ErrorEnvelope interface.
 */
export function instanceOfErrorEnvelope(value: object): value is ErrorEnvelope {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ErrorEnvelopeFromJSON(json: any): ErrorEnvelope {
    return ErrorEnvelopeFromJSONTyped(json, false);
}

export function ErrorEnvelopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorEnvelope {
    if (json == null) {
        return json;
    }
    return {
        
        'error': ErrorBodyFromJSON(json['error']),
    };
}

export function ErrorEnvelopeToJSON(json: any): ErrorEnvelope {
    return ErrorEnvelopeToJSONTyped(json, false);
}

export function ErrorEnvelopeToJSONTyped(value?: ErrorEnvelope | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': ErrorBodyToJSON(value['error']),
    };
}

