/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobOutputInfo
 */
export interface JobOutputInfo {
    /**
     * 
     * @type {JobOutputInfoStateEnum}
     * @memberof JobOutputInfo
     */
    state: JobOutputInfoStateEnum;
    /**
     * Output container format ("mp4" or "mkv").
     * @type {string}
     * @memberof JobOutputInfo
     */
    container: string;
    /**
     * Whether the output file actually contains audio.
     * Reflects the muxed result, not the request flag — a
     * video-only source with audio requested will report false.
     * 
     * @type {boolean}
     * @memberof JobOutputInfo
     */
    audio: boolean;
    /**
     * Customer-requested output height, echoed back. Null when the
     * job ran at source dimensions (passthrough).
     * 
     * @type {number}
     * @memberof JobOutputInfo
     */
    target_height?: number;
    /**
     * Actual encoded output width in pixels (post-ffprobe). Null until
     * the job completes or if the probe failed.
     * 
     * @type {number}
     * @memberof JobOutputInfo
     */
    width?: number;
    /**
     * Actual encoded output height in pixels. See `width`.
     * @type {number}
     * @memberof JobOutputInfo
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof JobOutputInfo
     */
    bytes?: number;
    /**
     * 
     * @type {string}
     * @memberof JobOutputInfo
     */
    sha256?: string;
    /**
     * 
     * @type {Date}
     * @memberof JobOutputInfo
     */
    retention_expires_at?: Date;
}

/**
* @export
* @enum {string}
*/
export enum JobOutputInfoStateEnum {
    PENDING = 'pending',
    AVAILABLE = 'available'
}


/**
 * Check if a given object implements the JobOutputInfo interface.
 */
export function instanceOfJobOutputInfo(value: object): value is JobOutputInfo {
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('container' in value) || value['container'] === undefined) return false;
    if (!('audio' in value) || value['audio'] === undefined) return false;
    return true;
}

export function JobOutputInfoFromJSON(json: any): JobOutputInfo {
    return JobOutputInfoFromJSONTyped(json, false);
}

export function JobOutputInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobOutputInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'state': json['state'],
        'container': json['container'],
        'audio': json['audio'],
        'target_height': json['target_height'] == null ? undefined : json['target_height'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
        'bytes': json['bytes'] == null ? undefined : json['bytes'],
        'sha256': json['sha256'] == null ? undefined : json['sha256'],
        'retention_expires_at': json['retention_expires_at'] == null ? undefined : (new Date(json['retention_expires_at'])),
    };
}

export function JobOutputInfoToJSON(json: any): JobOutputInfo {
    return JobOutputInfoToJSONTyped(json, false);
}

export function JobOutputInfoToJSONTyped(value?: JobOutputInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'state': value['state'],
        'container': value['container'],
        'audio': value['audio'],
        'target_height': value['target_height'],
        'width': value['width'],
        'height': value['height'],
        'bytes': value['bytes'],
        'sha256': value['sha256'],
        'retention_expires_at': value['retention_expires_at'] == null ? value['retention_expires_at'] : value['retention_expires_at'].toISOString(),
    };
}

