/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Encoding profile ID. Coffee-themed naming: prep time maps to encode speed,
 * bare name is the 8-bit default (universal decoder compatibility),
 * `-10bit` suffix opts into HEVC Main10 for higher-quality playback on
 * newer decoders.
 * 
 * **8-bit (default):**
 * - `sophon-espresso` — fastest, lowest compression
 * - `sophon-cortado` — balanced speed and quality
 * - `sophon-americano` — slowest, highest compression
 * 
 * **10-bit (HEVC Main10):**
 * - `sophon-espresso-10bit`
 * - `sophon-cortado-10bit`
 * - `sophon-americano-10bit`
 * 
 * **Adaptive dispatcher:**
 * - `sophon-auto` — public opt-in profile. The worker classifies
 *   the source and records the concrete `effective_profile_id` on
 *   the job once dispatch resolves.
 * 
 * @export
 * @enum {string}
 */
export enum JobProfile {
    SOPHON_ESPRESSO = 'sophon-espresso',
    SOPHON_CORTADO = 'sophon-cortado',
    SOPHON_AMERICANO = 'sophon-americano',
    SOPHON_ESPRESSO_10BIT = 'sophon-espresso-10bit',
    SOPHON_CORTADO_10BIT = 'sophon-cortado-10bit',
    SOPHON_AMERICANO_10BIT = 'sophon-americano-10bit',
    SOPHON_AUTO = 'sophon-auto'
}


export function instanceOfJobProfile(value: any): boolean {
    for (const key in JobProfile) {
        if (Object.prototype.hasOwnProperty.call(JobProfile, key)) {
            if (JobProfile[key as keyof typeof JobProfile] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobProfileFromJSON(json: any): JobProfile {
    return JobProfileFromJSONTyped(json, false);
}

export function JobProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobProfile {
    return json as JobProfile;
}

export function JobProfileToJSON(value?: JobProfile | null): any {
    return value as any;
}

export function JobProfileToJSONTyped(value: any, ignoreDiscriminator: boolean): JobProfile {
    return value as JobProfile;
}

