/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobStatus } from './JobStatus';
import {
    JobStatusFromJSON,
    JobStatusFromJSONTyped,
    JobStatusToJSON,
    JobStatusToJSONTyped,
} from './JobStatus';

/**
 * 
 * @export
 * @interface JobProgress
 */
export interface JobProgress {
    /**
     * Current processing stage label (e.g. "probing", "encoding", "muxing").
     * @type {string}
     * @memberof JobProgress
     */
    stage?: string;
    /**
     * Canonical pipeline phase used for progress semantics.
     * @type {JobStatus}
     * @memberof JobProgress
     */
    phase: JobStatus;
    /**
     * 
     * @type {number}
     * @memberof JobProgress
     */
    percent: number;
    /**
     * Progress within the current phase. Null before active processing.
     * @type {number}
     * @memberof JobProgress
     */
    phase_percent?: number;
    /**
     * 
     * @type {number}
     * @memberof JobProgress
     */
    fps?: number;
    /**
     * 
     * @type {number}
     * @memberof JobProgress
     */
    eta_seconds?: number;
    /**
     * 
     * @type {number}
     * @memberof JobProgress
     */
    frames_done?: number;
    /**
     * 
     * @type {number}
     * @memberof JobProgress
     */
    frames_total?: number;
}



/**
 * Check if a given object implements the JobProgress interface.
 */
export function instanceOfJobProgress(value: object): value is JobProgress {
    if (!('phase' in value) || value['phase'] === undefined) return false;
    if (!('percent' in value) || value['percent'] === undefined) return false;
    return true;
}

export function JobProgressFromJSON(json: any): JobProgress {
    return JobProgressFromJSONTyped(json, false);
}

export function JobProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobProgress {
    if (json == null) {
        return json;
    }
    return {
        
        'stage': json['stage'] == null ? undefined : json['stage'],
        'phase': JobStatusFromJSON(json['phase']),
        'percent': json['percent'],
        'phase_percent': json['phase_percent'] == null ? undefined : json['phase_percent'],
        'fps': json['fps'] == null ? undefined : json['fps'],
        'eta_seconds': json['eta_seconds'] == null ? undefined : json['eta_seconds'],
        'frames_done': json['frames_done'] == null ? undefined : json['frames_done'],
        'frames_total': json['frames_total'] == null ? undefined : json['frames_total'],
    };
}

export function JobProgressToJSON(json: any): JobProgress {
    return JobProgressToJSONTyped(json, false);
}

export function JobProgressToJSONTyped(value?: JobProgress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stage': value['stage'],
        'phase': JobStatusToJSON(value['phase']),
        'percent': value['percent'],
        'phase_percent': value['phase_percent'],
        'fps': value['fps'],
        'eta_seconds': value['eta_seconds'],
        'frames_done': value['frames_done'],
        'frames_total': value['frames_total'],
    };
}

