/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  ## Client Libraries  For server-side application integrations, start with one of the official SOPHON client libraries. Current published version: `0.1.5`.  | Language | Package | Install | |---|---|---| | TypeScript / JavaScript | [`@liqhtworks/sophon-sdk`](https://www.npmjs.com/package/@liqhtworks/sophon-sdk) | `npm install @liqhtworks/sophon-sdk` | | Python | [`sophon-sdk`](https://pypi.org/project/sophon-sdk/) | `pip install sophon-sdk` | | Go | [`github.com/Liqhtworks/sophon-sdk-go`](https://github.com/Liqhtworks/sophon-sdk-go) | `go get github.com/Liqhtworks/sophon-sdk-go@latest` |  These libraries are generated from this OpenAPI document and include the generated endpoint clients plus helpers for chunked uploads, terminal job polling, upload-backed job source construction, and webhook signature verification.  We do not currently publish official SDKs for Ruby, Java, Kotlin, Swift, PHP, .NET, or Rust. Use the REST API directly from those languages.  Authentication is via Bearer API key or session cookie. Create API keys in the SOPHON dashboard at https://sophon.rs/account/general and pass them as `Authorization: Bearer xt_live_...`. All POST endpoints require an `Idempotency-Key` header. List endpoints use opaque cursor-based pagination.  See **SDKs** for install commands and quickstarts. See **Integration example** for a production state-machine pattern and raw HTTP adapter guidance. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobStatus } from './JobStatus';
import {
    JobStatusFromJSON,
    JobStatusFromJSONTyped,
    JobStatusToJSON,
    JobStatusToJSONTyped,
} from './JobStatus';
import type { JobSourceInfo } from './JobSourceInfo';
import {
    JobSourceInfoFromJSON,
    JobSourceInfoFromJSONTyped,
    JobSourceInfoToJSON,
    JobSourceInfoToJSONTyped,
} from './JobSourceInfo';
import type { JobProfile } from './JobProfile';
import {
    JobProfileFromJSON,
    JobProfileFromJSONTyped,
    JobProfileToJSON,
    JobProfileToJSONTyped,
} from './JobProfile';
import type { JobOutputInfo } from './JobOutputInfo';
import {
    JobOutputInfoFromJSON,
    JobOutputInfoFromJSONTyped,
    JobOutputInfoToJSON,
    JobOutputInfoToJSONTyped,
} from './JobOutputInfo';
import type { JobProgress } from './JobProgress';
import {
    JobProgressFromJSON,
    JobProgressFromJSONTyped,
    JobProgressToJSON,
    JobProgressToJSONTyped,
} from './JobProgress';

/**
 * 
 * @export
 * @interface JobResponse
 */
export interface JobResponse {
    /**
     * 
     * @type {string}
     * @memberof JobResponse
     */
    id: string;
    /**
     * 
     * @type {JobStatus}
     * @memberof JobResponse
     */
    status: JobStatus;
    /**
     * 
     * @type {string}
     * @memberof JobResponse
     */
    status_reason?: string;
    /**
     * 
     * @type {number}
     * @memberof JobResponse
     */
    attempt: number;
    /**
     * Whether the job can still be retried (attempt < max_attempts and not terminal).
     * @type {boolean}
     * @memberof JobResponse
     */
    retryable: boolean;
    /**
     * Public profile ID submitted by the customer. For adaptive jobs this
     * stays `sophon-auto`; see `effective_profile_id` for the worker's
     * resolved concrete profile.
     * 
     * @type {JobProfile}
     * @memberof JobResponse
     */
    profile: JobProfile;
    /**
     * Concrete profile resolved by the worker. Omitted until dispatch
     * resolves. On explicit-profile jobs this equals `profile`. On
     * `sophon-auto` jobs this is a variant identifier recording
     * which path the API routed the source through; exact encoder
     * settings for a given variant may be updated between releases
     * as the adaptive logic is tuned.
     * 
     * @type {string}
     * @memberof JobResponse
     */
    effective_profile_id?: string;
    /**
     * 
     * @type {JobSourceInfo}
     * @memberof JobResponse
     */
    source: JobSourceInfo;
    /**
     * 
     * @type {JobProgress}
     * @memberof JobResponse
     */
    progress: JobProgress;
    /**
     * 
     * @type {JobOutputInfo}
     * @memberof JobResponse
     */
    output: JobOutputInfo;
    /**
     * Arbitrary JSON object attached to a job. Keys and values are passed
     * through unchanged to webhook deliveries and echoed on job reads. The
     * serialized representation must not exceed 16 KiB. Free-form; SDKs
     * surface this as a `Record<string, unknown>` / `dict[str, Any]` /
     * `map[string]interface{}` depending on language.
     * 
     * @type {{ [key: string]: any; }}
     * @memberof JobResponse
     */
    metadata: { [key: string]: any; };
    /**
     * 
     * @type {Date}
     * @memberof JobResponse
     */
    created_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof JobResponse
     */
    started_at?: Date;
    /**
     * 
     * @type {Date}
     * @memberof JobResponse
     */
    completed_at?: Date;
    /**
     * 
     * @type {string}
     * @memberof JobResponse
     */
    error?: string;
}



/**
 * Check if a given object implements the JobResponse interface.
 */
export function instanceOfJobResponse(value: object): value is JobResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('attempt' in value) || value['attempt'] === undefined) return false;
    if (!('retryable' in value) || value['retryable'] === undefined) return false;
    if (!('profile' in value) || value['profile'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function JobResponseFromJSON(json: any): JobResponse {
    return JobResponseFromJSONTyped(json, false);
}

export function JobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': JobStatusFromJSON(json['status']),
        'status_reason': json['status_reason'] == null ? undefined : json['status_reason'],
        'attempt': json['attempt'],
        'retryable': json['retryable'],
        'profile': JobProfileFromJSON(json['profile']),
        'effective_profile_id': json['effective_profile_id'] == null ? undefined : json['effective_profile_id'],
        'source': JobSourceInfoFromJSON(json['source']),
        'progress': JobProgressFromJSON(json['progress']),
        'output': JobOutputInfoFromJSON(json['output']),
        'metadata': json['metadata'],
        'created_at': (new Date(json['created_at'])),
        'started_at': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'completed_at': json['completed_at'] == null ? undefined : (new Date(json['completed_at'])),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function JobResponseToJSON(json: any): JobResponse {
    return JobResponseToJSONTyped(json, false);
}

export function JobResponseToJSONTyped(value?: JobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': JobStatusToJSON(value['status']),
        'status_reason': value['status_reason'],
        'attempt': value['attempt'],
        'retryable': value['retryable'],
        'profile': JobProfileToJSON(value['profile']),
        'effective_profile_id': value['effective_profile_id'],
        'source': JobSourceInfoToJSON(value['source']),
        'progress': JobProgressToJSON(value['progress']),
        'output': JobOutputInfoToJSON(value['output']),
        'metadata': value['metadata'],
        'created_at': value['created_at'].toISOString(),
        'started_at': value['started_at'] == null ? value['started_at'] : value['started_at'].toISOString(),
        'completed_at': value['completed_at'] == null ? value['completed_at'] : value['completed_at'].toISOString(),
        'error': value['error'],
    };
}

