/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Discriminator for `JobSource` variants.
 * @export
 * @enum {string}
 */
export enum JobSourceType {
    UPLOAD = 'upload'
}


export function instanceOfJobSourceType(value: any): boolean {
    for (const key in JobSourceType) {
        if (Object.prototype.hasOwnProperty.call(JobSourceType, key)) {
            if (JobSourceType[key as keyof typeof JobSourceType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobSourceTypeFromJSON(json: any): JobSourceType {
    return JobSourceTypeFromJSONTyped(json, false);
}

export function JobSourceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobSourceType {
    return json as JobSourceType;
}

export function JobSourceTypeToJSON(value?: JobSourceType | null): any {
    return value as any;
}

export function JobSourceTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): JobSourceType {
    return value as JobSourceType;
}

