/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobSourceInfo
 */
export interface JobSourceInfo {
    /**
     * Original file name of the source.
     * @type {string}
     * @memberof JobSourceInfo
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof JobSourceInfo
     */
    bytes?: number;
    /**
     * SHA-256 hex digest of the source file.
     * @type {string}
     * @memberof JobSourceInfo
     */
    sha256: string;
    /**
     * 
     * @type {number}
     * @memberof JobSourceInfo
     */
    duration_seconds?: number;
    /**
     * 
     * @type {string}
     * @memberof JobSourceInfo
     */
    resolution?: string;
    /**
     * 
     * @type {string}
     * @memberof JobSourceInfo
     */
    frame_rate?: string;
}

/**
 * Check if a given object implements the JobSourceInfo interface.
 */
export function instanceOfJobSourceInfo(value: object): value is JobSourceInfo {
    if (!('sha256' in value) || value['sha256'] === undefined) return false;
    return true;
}

export function JobSourceInfoFromJSON(json: any): JobSourceInfo {
    return JobSourceInfoFromJSONTyped(json, false);
}

export function JobSourceInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobSourceInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'bytes': json['bytes'] == null ? undefined : json['bytes'],
        'sha256': json['sha256'],
        'duration_seconds': json['duration_seconds'] == null ? undefined : json['duration_seconds'],
        'resolution': json['resolution'] == null ? undefined : json['resolution'],
        'frame_rate': json['frame_rate'] == null ? undefined : json['frame_rate'],
    };
}

export function JobSourceInfoToJSON(json: any): JobSourceInfo {
    return JobSourceInfoToJSONTyped(json, false);
}

export function JobSourceInfoToJSONTyped(value?: JobSourceInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'bytes': value['bytes'],
        'sha256': value['sha256'],
        'duration_seconds': value['duration_seconds'],
        'resolution': value['resolution'],
        'frame_rate': value['frame_rate'],
    };
}

