/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  ## Client Libraries  For server-side application integrations, start with one of the official SOPHON client libraries. Current published version: `0.1.5`.  | Language | Package | Install | |---|---|---| | TypeScript / JavaScript | [`@liqhtworks/sophon-sdk`](https://www.npmjs.com/package/@liqhtworks/sophon-sdk) | `npm install @liqhtworks/sophon-sdk` | | Python | [`sophon-sdk`](https://pypi.org/project/sophon-sdk/) | `pip install sophon-sdk` | | Go | [`github.com/Liqhtworks/sophon-sdk-go`](https://github.com/Liqhtworks/sophon-sdk-go) | `go get github.com/Liqhtworks/sophon-sdk-go@latest` |  These libraries are generated from this OpenAPI document and include the generated endpoint clients plus helpers for chunked uploads, terminal job polling, upload-backed job source construction, and webhook signature verification.  We do not currently publish official SDKs for Ruby, Java, Kotlin, Swift, PHP, .NET, or Rust. Use the REST API directly from those languages.  Authentication is via Bearer API key or session cookie. Create API keys in the SOPHON dashboard at https://sophon.rs/account/general and pass them as `Authorization: Bearer xt_live_...`. All POST endpoints require an `Idempotency-Key` header. List endpoints use opaque cursor-based pagination.  See **SDKs** for install commands and quickstarts. See **Integration example** for a production state-machine pattern and raw HTTP adapter guidance. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobResponse } from './JobResponse';
import {
    JobResponseFromJSON,
    JobResponseFromJSONTyped,
    JobResponseToJSON,
    JobResponseToJSONTyped,
} from './JobResponse';

/**
 * 
 * @export
 * @interface ListJobsResponse
 */
export interface ListJobsResponse {
    /**
     * 
     * @type {Array<JobResponse>}
     * @memberof ListJobsResponse
     */
    jobs: Array<JobResponse>;
    /**
     * Opaque cursor for the next page. Null when no more results.
     * @type {string}
     * @memberof ListJobsResponse
     */
    next_cursor?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListJobsResponse
     */
    has_more: boolean;
}

/**
 * Check if a given object implements the ListJobsResponse interface.
 */
export function instanceOfListJobsResponse(value: object): value is ListJobsResponse {
    if (!('jobs' in value) || value['jobs'] === undefined) return false;
    if (!('has_more' in value) || value['has_more'] === undefined) return false;
    return true;
}

export function ListJobsResponseFromJSON(json: any): ListJobsResponse {
    return ListJobsResponseFromJSONTyped(json, false);
}

export function ListJobsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListJobsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobs': ((json['jobs'] as Array<any>).map(JobResponseFromJSON)),
        'next_cursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'has_more': json['has_more'],
    };
}

export function ListJobsResponseToJSON(json: any): ListJobsResponse {
    return ListJobsResponseToJSONTyped(json, false);
}

export function ListJobsResponseToJSONTyped(value?: ListJobsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobs': ((value['jobs'] as Array<any>).map(JobResponseToJSON)),
        'next_cursor': value['next_cursor'],
        'has_more': value['has_more'],
    };
}

