/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobResponse } from './JobResponse';
import {
    JobResponseFromJSON,
    JobResponseFromJSONTyped,
    JobResponseToJSON,
    JobResponseToJSONTyped,
} from './JobResponse';

/**
 * 
 * @export
 * @interface ListJobsResponse
 */
export interface ListJobsResponse {
    /**
     * 
     * @type {Array<JobResponse>}
     * @memberof ListJobsResponse
     */
    jobs: Array<JobResponse>;
    /**
     * Opaque cursor for the next page. Null when no more results.
     * @type {string}
     * @memberof ListJobsResponse
     */
    next_cursor?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListJobsResponse
     */
    has_more: boolean;
}

/**
 * Check if a given object implements the ListJobsResponse interface.
 */
export function instanceOfListJobsResponse(value: object): value is ListJobsResponse {
    if (!('jobs' in value) || value['jobs'] === undefined) return false;
    if (!('has_more' in value) || value['has_more'] === undefined) return false;
    return true;
}

export function ListJobsResponseFromJSON(json: any): ListJobsResponse {
    return ListJobsResponseFromJSONTyped(json, false);
}

export function ListJobsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListJobsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobs': ((json['jobs'] as Array<any>).map(JobResponseFromJSON)),
        'next_cursor': json['next_cursor'] == null ? undefined : json['next_cursor'],
        'has_more': json['has_more'],
    };
}

export function ListJobsResponseToJSON(json: any): ListJobsResponse {
    return ListJobsResponseToJSONTyped(json, false);
}

export function ListJobsResponseToJSONTyped(value?: ListJobsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobs': ((value['jobs'] as Array<any>).map(JobResponseToJSON)),
        'next_cursor': value['next_cursor'],
        'has_more': value['has_more'],
    };
}

