/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Output container format. MP4 is widely compatible; MKV
 * supports a broader range of audio codecs for passthrough.
 * 
 * @export
 * @enum {string}
 */
export enum OutputContainer {
    MP4 = 'mp4',
    MKV = 'mkv'
}


export function instanceOfOutputContainer(value: any): boolean {
    for (const key in OutputContainer) {
        if (Object.prototype.hasOwnProperty.call(OutputContainer, key)) {
            if (OutputContainer[key as keyof typeof OutputContainer] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OutputContainerFromJSON(json: any): OutputContainer {
    return OutputContainerFromJSONTyped(json, false);
}

export function OutputContainerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputContainer {
    return json as OutputContainer;
}

export function OutputContainerToJSON(value?: OutputContainer | null): any {
    return value as any;
}

export function OutputContainerToJSONTyped(value: any, ignoreDiscriminator: boolean): OutputContainer {
    return value as OutputContainer;
}

