/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  ## Client Libraries  For server-side application integrations, start with one of the official SOPHON client libraries. Current published version: `0.1.5`.  | Language | Package | Install | |---|---|---| | TypeScript / JavaScript | [`@liqhtworks/sophon-sdk`](https://www.npmjs.com/package/@liqhtworks/sophon-sdk) | `npm install @liqhtworks/sophon-sdk` | | Python | [`sophon-sdk`](https://pypi.org/project/sophon-sdk/) | `pip install sophon-sdk` | | Go | [`github.com/Liqhtworks/sophon-sdk-go`](https://github.com/Liqhtworks/sophon-sdk-go) | `go get github.com/Liqhtworks/sophon-sdk-go@latest` |  These libraries are generated from this OpenAPI document and include the generated endpoint clients plus helpers for chunked uploads, terminal job polling, upload-backed job source construction, and webhook signature verification.  We do not currently publish official SDKs for Ruby, Java, Kotlin, Swift, PHP, .NET, or Rust. Use the REST API directly from those languages.  Authentication is via Bearer API key or session cookie. Create API keys in the SOPHON dashboard at https://sophon.rs/account/general and pass them as `Authorization: Bearer xt_live_...`. All POST endpoints require an `Idempotency-Key` header. List endpoints use opaque cursor-based pagination.  See **SDKs** for install commands and quickstarts. See **Integration example** for a production state-machine pattern and raw HTTP adapter guidance. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Output container format. MP4 is widely compatible; MKV
 * supports a broader range of audio codecs for passthrough.
 * 
 * @export
 * @enum {string}
 */
export enum OutputContainer {
    MP4 = 'mp4',
    MKV = 'mkv'
}


export function instanceOfOutputContainer(value: any): boolean {
    for (const key in OutputContainer) {
        if (Object.prototype.hasOwnProperty.call(OutputContainer, key)) {
            if (OutputContainer[key as keyof typeof OutputContainer] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OutputContainerFromJSON(json: any): OutputContainer {
    return OutputContainerFromJSONTyped(json, false);
}

export function OutputContainerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputContainer {
    return json as OutputContainer;
}

export function OutputContainerToJSON(value?: OutputContainer | null): any {
    return value as any;
}

export function OutputContainerToJSONTyped(value: any, ignoreDiscriminator: boolean): OutputContainer {
    return value as OutputContainer;
}

