/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadyResponse
 */
export interface ReadyResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ReadyResponse
     */
    ready: boolean;
    /**
     * Names of failed readiness checks (database, disk_critical, draining, workers_dead).
     * @type {Array<string>}
     * @memberof ReadyResponse
     */
    checks_failed?: Array<string>;
}

/**
 * Check if a given object implements the ReadyResponse interface.
 */
export function instanceOfReadyResponse(value: object): value is ReadyResponse {
    if (!('ready' in value) || value['ready'] === undefined) return false;
    return true;
}

export function ReadyResponseFromJSON(json: any): ReadyResponse {
    return ReadyResponseFromJSONTyped(json, false);
}

export function ReadyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ready': json['ready'],
        'checks_failed': json['checks_failed'] == null ? undefined : json['checks_failed'],
    };
}

export function ReadyResponseToJSON(json: any): ReadyResponse {
    return ReadyResponseToJSONTyped(json, false);
}

export function ReadyResponseToJSONTyped(value?: ReadyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ready': value['ready'],
        'checks_failed': value['checks_failed'],
    };
}

