/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobSourceType } from './JobSourceType';
import {
    JobSourceTypeFromJSON,
    JobSourceTypeFromJSONTyped,
    JobSourceTypeToJSON,
    JobSourceTypeToJSONTyped,
} from './JobSourceType';

/**
 * Source backed by a completed chunked upload session.
 * @export
 * @interface UploadJobSource
 */
export interface UploadJobSource {
    /**
     * 
     * @type {JobSourceType}
     * @memberof UploadJobSource
     */
    type: JobSourceType;
    /**
     * ID of a completed upload session.
     * @type {string}
     * @memberof UploadJobSource
     */
    upload_id: string;
}



/**
 * Check if a given object implements the UploadJobSource interface.
 */
export function instanceOfUploadJobSource(value: object): value is UploadJobSource {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('upload_id' in value) || value['upload_id'] === undefined) return false;
    return true;
}

export function UploadJobSourceFromJSON(json: any): UploadJobSource {
    return UploadJobSourceFromJSONTyped(json, false);
}

export function UploadJobSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadJobSource {
    if (json == null) {
        return json;
    }
    return {
        
        'type': JobSourceTypeFromJSON(json['type']),
        'upload_id': json['upload_id'],
    };
}

export function UploadJobSourceToJSON(json: any): UploadJobSource {
    return UploadJobSourceToJSONTyped(json, false);
}

export function UploadJobSourceToJSONTyped(value?: UploadJobSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': JobSourceTypeToJSON(value['type']),
        'upload_id': value['upload_id'],
    };
}

