/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadStatusResponse
 */
export interface UploadStatusResponse {
    /**
     * 
     * @type {string}
     * @memberof UploadStatusResponse
     */
    id: string;
    /**
     * 
     * @type {UploadStatusResponseStatusEnum}
     * @memberof UploadStatusResponse
     */
    status: UploadStatusResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UploadStatusResponse
     */
    file_name: string;
    /**
     * 
     * @type {number}
     * @memberof UploadStatusResponse
     */
    total_chunks: number;
    /**
     * Array of 0-indexed part numbers that have been received.
     * @type {Array<number>}
     * @memberof UploadStatusResponse
     */
    received_chunks: Array<number>;
    /**
     * 
     * @type {Date}
     * @memberof UploadStatusResponse
     */
    expires_at: Date;
    /**
     * Source media width in pixels, populated from ffprobe after upload
     * assembly. Null for uploads in `initiated`/`uploading` state or
     * when probe failed.
     * 
     * @type {number}
     * @memberof UploadStatusResponse
     */
    source_width?: number;
    /**
     * Source media height in pixels. See `source_width`.
     * @type {number}
     * @memberof UploadStatusResponse
     */
    source_height?: number;
    /**
     * Source media duration in seconds, from ffprobe after upload
     * assembly. Used by the webapp free-tier budget check to compute
     * realistic billable_seconds (5-second ceiling rounding).
     * 
     * @type {number}
     * @memberof UploadStatusResponse
     */
    source_duration_seconds?: number;
}

/**
* @export
* @enum {string}
*/
export enum UploadStatusResponseStatusEnum {
    UPLOADING = 'uploading',
    ASSEMBLING = 'assembling',
    COMPLETED = 'completed',
    CANCELED = 'canceled'
}


/**
 * Check if a given object implements the UploadStatusResponse interface.
 */
export function instanceOfUploadStatusResponse(value: object): value is UploadStatusResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('file_name' in value) || value['file_name'] === undefined) return false;
    if (!('total_chunks' in value) || value['total_chunks'] === undefined) return false;
    if (!('received_chunks' in value) || value['received_chunks'] === undefined) return false;
    if (!('expires_at' in value) || value['expires_at'] === undefined) return false;
    return true;
}

export function UploadStatusResponseFromJSON(json: any): UploadStatusResponse {
    return UploadStatusResponseFromJSONTyped(json, false);
}

export function UploadStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'file_name': json['file_name'],
        'total_chunks': json['total_chunks'],
        'received_chunks': json['received_chunks'],
        'expires_at': (new Date(json['expires_at'])),
        'source_width': json['source_width'] == null ? undefined : json['source_width'],
        'source_height': json['source_height'] == null ? undefined : json['source_height'],
        'source_duration_seconds': json['source_duration_seconds'] == null ? undefined : json['source_duration_seconds'],
    };
}

export function UploadStatusResponseToJSON(json: any): UploadStatusResponse {
    return UploadStatusResponseToJSONTyped(json, false);
}

export function UploadStatusResponseToJSONTyped(value?: UploadStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'file_name': value['file_name'],
        'total_chunks': value['total_chunks'],
        'received_chunks': value['received_chunks'],
        'expires_at': value['expires_at'].toISOString(),
        'source_width': value['source_width'],
        'source_height': value['source_height'],
        'source_duration_seconds': value['source_duration_seconds'],
    };
}

