/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadPartResponse
 */
export interface UploadPartResponse {
    /**
     * 
     * @type {number}
     * @memberof UploadPartResponse
     */
    part_number: number;
    /**
     * 
     * @type {boolean}
     * @memberof UploadPartResponse
     */
    received: boolean;
}

/**
 * Check if a given object implements the UploadPartResponse interface.
 */
export function instanceOfUploadPartResponse(value: object): value is UploadPartResponse {
    if (!('part_number' in value) || value['part_number'] === undefined) return false;
    if (!('received' in value) || value['received'] === undefined) return false;
    return true;
}

export function UploadPartResponseFromJSON(json: any): UploadPartResponse {
    return UploadPartResponseFromJSONTyped(json, false);
}

export function UploadPartResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadPartResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'part_number': json['part_number'],
        'received': json['received'],
    };
}

export function UploadPartResponseToJSON(json: any): UploadPartResponse {
    return UploadPartResponseToJSONTyped(json, false);
}

export function UploadPartResponseToJSONTyped(value?: UploadPartResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'part_number': value['part_number'],
        'received': value['received'],
    };
}

