/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  ## Client Libraries  For server-side application integrations, start with one of the official SOPHON client libraries. Current published version: `0.1.5`.  | Language | Package | Install | |---|---|---| | TypeScript / JavaScript | [`@liqhtworks/sophon-sdk`](https://www.npmjs.com/package/@liqhtworks/sophon-sdk) | `npm install @liqhtworks/sophon-sdk` | | Python | [`sophon-sdk`](https://pypi.org/project/sophon-sdk/) | `pip install sophon-sdk` | | Go | [`github.com/Liqhtworks/sophon-sdk-go`](https://github.com/Liqhtworks/sophon-sdk-go) | `go get github.com/Liqhtworks/sophon-sdk-go@latest` |  These libraries are generated from this OpenAPI document and include the generated endpoint clients plus helpers for chunked uploads, terminal job polling, upload-backed job source construction, and webhook signature verification.  We do not currently publish official SDKs for Ruby, Java, Kotlin, Swift, PHP, .NET, or Rust. Use the REST API directly from those languages.  Authentication is via Bearer API key or session cookie. Create API keys in the SOPHON dashboard at https://sophon.rs/account/general and pass them as `Authorization: Bearer xt_live_...`. All POST endpoints require an `Idempotency-Key` header. List endpoints use opaque cursor-based pagination.  See **SDKs** for install commands and quickstarts. See **Integration example** for a production state-machine pattern and raw HTTP adapter guidance. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookListItem } from './WebhookListItem';
import {
    WebhookListItemFromJSON,
    WebhookListItemFromJSONTyped,
    WebhookListItemToJSON,
    WebhookListItemToJSONTyped,
} from './WebhookListItem';

/**
 * 
 * @export
 * @interface WebhookListResponse
 */
export interface WebhookListResponse {
    /**
     * 
     * @type {Array<WebhookListItem>}
     * @memberof WebhookListResponse
     */
    webhooks: Array<WebhookListItem>;
}

/**
 * Check if a given object implements the WebhookListResponse interface.
 */
export function instanceOfWebhookListResponse(value: object): value is WebhookListResponse {
    if (!('webhooks' in value) || value['webhooks'] === undefined) return false;
    return true;
}

export function WebhookListResponseFromJSON(json: any): WebhookListResponse {
    return WebhookListResponseFromJSONTyped(json, false);
}

export function WebhookListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'webhooks': ((json['webhooks'] as Array<any>).map(WebhookListItemFromJSON)),
    };
}

export function WebhookListResponseToJSON(json: any): WebhookListResponse {
    return WebhookListResponseToJSONTyped(json, false);
}

export function WebhookListResponseToJSONTyped(value?: WebhookListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'webhooks': ((value['webhooks'] as Array<any>).map(WebhookListItemToJSON)),
    };
}

