/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookResponse
 */
export interface WebhookResponse {
    /**
     * 
     * @type {string}
     * @memberof WebhookResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookResponse
     */
    url: string;
    /**
     * HMAC signing secret (64-char hex string, 32 random bytes).
     * Only returned on creation. Use to verify webhook delivery signatures.
     * 
     * @type {string}
     * @memberof WebhookResponse
     */
    secret: string;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookResponse
     */
    active: boolean;
    /**
     * 
     * @type {Date}
     * @memberof WebhookResponse
     */
    created_at: Date;
}

/**
 * Check if a given object implements the WebhookResponse interface.
 */
export function instanceOfWebhookResponse(value: object): value is WebhookResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('secret' in value) || value['secret'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function WebhookResponseFromJSON(json: any): WebhookResponse {
    return WebhookResponseFromJSONTyped(json, false);
}

export function WebhookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'secret': json['secret'],
        'active': json['active'],
        'created_at': (new Date(json['created_at'])),
    };
}

export function WebhookResponseToJSON(json: any): WebhookResponse {
    return WebhookResponseToJSONTyped(json, false);
}

export function WebhookResponseToJSONTyped(value?: WebhookResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
        'secret': value['secret'],
        'active': value['active'],
        'created_at': value['created_at'].toISOString(),
    };
}

