/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookListItem } from './WebhookListItem';
import {
    WebhookListItemFromJSON,
    WebhookListItemFromJSONTyped,
    WebhookListItemToJSON,
    WebhookListItemToJSONTyped,
} from './WebhookListItem';

/**
 * 
 * @export
 * @interface WebhookListResponse
 */
export interface WebhookListResponse {
    /**
     * 
     * @type {Array<WebhookListItem>}
     * @memberof WebhookListResponse
     */
    webhooks: Array<WebhookListItem>;
}

/**
 * Check if a given object implements the WebhookListResponse interface.
 */
export function instanceOfWebhookListResponse(value: object): value is WebhookListResponse {
    if (!('webhooks' in value) || value['webhooks'] === undefined) return false;
    return true;
}

export function WebhookListResponseFromJSON(json: any): WebhookListResponse {
    return WebhookListResponseFromJSONTyped(json, false);
}

export function WebhookListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'webhooks': ((json['webhooks'] as Array<any>).map(WebhookListItemFromJSON)),
    };
}

export function WebhookListResponseToJSON(json: any): WebhookListResponse {
    return WebhookListResponseToJSONTyped(json, false);
}

export function WebhookListResponseToJSONTyped(value?: WebhookListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'webhooks': ((value['webhooks'] as Array<any>).map(WebhookListItemToJSON)),
    };
}

