/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookListItem
 */
export interface WebhookListItem {
    /**
     * 
     * @type {string}
     * @memberof WebhookListItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookListItem
     */
    url: string;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookListItem
     */
    active: boolean;
    /**
     * 
     * @type {Date}
     * @memberof WebhookListItem
     */
    created_at: Date;
}

/**
 * Check if a given object implements the WebhookListItem interface.
 */
export function instanceOfWebhookListItem(value: object): value is WebhookListItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    return true;
}

export function WebhookListItemFromJSON(json: any): WebhookListItem {
    return WebhookListItemFromJSONTyped(json, false);
}

export function WebhookListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookListItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'active': json['active'],
        'created_at': (new Date(json['created_at'])),
    };
}

export function WebhookListItemToJSON(json: any): WebhookListItem {
    return WebhookListItemToJSONTyped(json, false);
}

export function WebhookListItemToJSONTyped(value?: WebhookListItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
        'active': value['active'],
        'created_at': value['created_at'].toISOString(),
    };
}

