/* tslint:disable */
/* eslint-disable */
/**
 * SOPHON Encoding API
 * REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Payload delivered to registered webhook endpoints on terminal job events.
 * Signed with HMAC-SHA256 over `"{timestamp}.{raw_body}"` using the
 * per-webhook secret. Consumers must verify the signature before processing.
 * 
 * @export
 * @interface WebhookDeliveryPayload
 */
export interface WebhookDeliveryPayload {
    /**
     * Unique delivery event ID for deduplication.
     * @type {string}
     * @memberof WebhookDeliveryPayload
     */
    event_id: string;
    /**
     * Event type.
     * @type {WebhookDeliveryPayloadTypeEnum}
     * @memberof WebhookDeliveryPayload
     */
    type: WebhookDeliveryPayloadTypeEnum;
    /**
     * ISO 8601 timestamp of the event.
     * @type {Date}
     * @memberof WebhookDeliveryPayload
     */
    timestamp: Date;
    /**
     * The job that reached a terminal state.
     * @type {string}
     * @memberof WebhookDeliveryPayload
     */
    job_id: string;
    /**
     * Terminal job status.
     * @type {WebhookDeliveryPayloadStatusEnum}
     * @memberof WebhookDeliveryPayload
     */
    status: WebhookDeliveryPayloadStatusEnum;
    /**
     * Opaque metadata from the original job submission.
     * @type {{ [key: string]: any; }}
     * @memberof WebhookDeliveryPayload
     */
    metadata: { [key: string]: any; };
}

/**
* @export
* @enum {string}
*/
export enum WebhookDeliveryPayloadTypeEnum {
    JOB_COMPLETED = 'job.completed',
    JOB_FAILED = 'job.failed',
    JOB_CANCELED = 'job.canceled'
}
/**
* @export
* @enum {string}
*/
export enum WebhookDeliveryPayloadStatusEnum {
    COMPLETED = 'completed',
    FAILED = 'failed',
    CANCELED = 'canceled'
}


/**
 * Check if a given object implements the WebhookDeliveryPayload interface.
 */
export function instanceOfWebhookDeliveryPayload(value: object): value is WebhookDeliveryPayload {
    if (!('event_id' in value) || value['event_id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('job_id' in value) || value['job_id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function WebhookDeliveryPayloadFromJSON(json: any): WebhookDeliveryPayload {
    return WebhookDeliveryPayloadFromJSONTyped(json, false);
}

export function WebhookDeliveryPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDeliveryPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'event_id': json['event_id'],
        'type': json['type'],
        'timestamp': (new Date(json['timestamp'])),
        'job_id': json['job_id'],
        'status': json['status'],
        'metadata': json['metadata'],
    };
}

export function WebhookDeliveryPayloadToJSON(json: any): WebhookDeliveryPayload {
    return WebhookDeliveryPayloadToJSONTyped(json, false);
}

export function WebhookDeliveryPayloadToJSONTyped(value?: WebhookDeliveryPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_id': value['event_id'],
        'type': value['type'],
        'timestamp': value['timestamp'].toISOString(),
        'job_id': value['job_id'],
        'status': value['status'],
        'metadata': value['metadata'],
    };
}

